config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'products', to: 'pages#products'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def products
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contactanos</h3>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <%= form_for "/contacts" do |f| %>
          <div class="form-group">
            <%= f.label :nombre %>
            <%= f.text_field :nombre, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :comentario %>
            <%= f.text_area :commentario, class: 'form-control' %>
          </div>
          
          <%= f.submit 'Enviar', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magas del Sur</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
          <%= link_to "/", class: "text-center container-fluid" do %>
            <%= image_tag("magas-logo.png", :alt => "magas logo", :size => "286x231") %>
          <% end %>
        <div class="navbar-header">
          <div>
            
            </div><button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!--<div class="toggle-text navbar-toggle">MENÚ</div>-->
          </div>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Inicio", "/", class: "nav-text" %></li>
            <li><%= link_to "Quienes somos", about_path, class: "nav-text" %></li>
            <li><%=link_to "Productos", products_path, class: "nav-text" %></li>
            <li><a href="/contact-us" class="nav-text">Contactenos</a></li>
          </ul>
        </div>
        
        
    <!--<nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">Magas del Sur</a>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/about">Quienes somos</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
  <h2>Quienes somos</h2>
  <p>Magas del Sur es una empresa formada por un círculo de mujeres alquimistas 
  que se unieron para recrear antiguas recetas mágicas que permiten hacer la 
  vida más sana y vivir en un estado de eterna juventud. Magas del sur trabaja 
  en el Sur del Planeta, desde Argentina para el mundo.
Los productos manufacturados por Magas del Sur, están elaborados con aceites 
esenciales y elementos naturales puros, seleccionados minuciosamente.</p>
<p>Son confeccionados en estado meditativo y en comunión espiritual con los 
elementales del aire, fuego, tierra y agua, y seres de los planos elevados del 
alma.</p>
<p>Magas del sur entrega en sus productos armonía, alegría y bienestar para 
mejorar la calidad de vida.</p>
<h3>Pastas Alquímicas</h3>
<p>Las pastas alquímicas son preparados hechos de resinas, especies y aceites 
esenciales molidos en el mortero.</p>
<p>Las pastas alquimicas se colocan sobre un carboncito encendido el cual con 
el calor hace entrar en combustión la pasta la cual emana humos perfumados que 
abrazan todos los ambientes para lograr los objetivos de acuerdo a la fragancia 
que se seleccione.</p>
<h3>Jabones y armonizadores alquímicos</h3>
<p>Los jabones alquímicos están preparados para ser usados sobre todo tipo de 
piel, son de glicerina natural y tienen agregados de aceites esenciales que 
provocan diversos efectos según la fragancia seleccionada.</p>
<p>Los armonizadores alquímicos son de uso personal, para rociar sobre el 
cuerpo o la ropa, al igual que los jabones provocaran el efecto según la 
fragancia seleccionada.</p>
<h3>Fragancias</h3>
<h4>Liblim (LL) </h4>
<p>Es una fragancia para la limpieza y liberación de energía. Remueve 
profundamente bloqueos, limitaciones y miedos.</p>
<h4>Abuar (AB)</h4>
<p>Es una fragancia para dar armonía y abrir las puertas a la abundancia en 
todos los niveles. Abundancia de conocimientos, de paz, de trabajo, de 
remuneraciones.</p>
<h4>Alam (AA)</h4>
<p>Es una fragancia que tiene combinaciones de esencias que darán alegría, y 
amor. Apertura a otros seres.</p>
<h4>Amomir (AM)</h4>
<p>Es una fragancia para la relajación y preparación al descanso profundo y el 
buen dormir. Ideal para niños.</p>

</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <%= image_tag("magas1.png", :alt => "magas kit") %>
  <h2>Jabones, sales de baño, aromatizadores, pastas alquímicas, palo santo</h2>
  <h3>¡Envíos a todo el país!</h3>
  
  <div class="row" id="icons">
    <div class="col-md-4" id="calidad">
      <i class="fas fa-medal fa-5x"></i>
      <h3>CALIDAD</h3>
      <p> Lorem ipsum</p>
    </div>
    <div class="col-md-4" id="compromiso">
      <i class="fas fa-handshake fa-5x"></i>
    <h3>COMPROMISO</h3>
    <p> Lorem ipsum</p>
    </div>
    <div class="col-md-4" id="accesibilidad">
      <i class="fas fa-shopping-bag fa-5x"></i>
    <h3>ACCESIBILIDAD</h3>
    <p> Lorem ipsum</p>
    </div>
  </div>
  
  <div class="row" id="about">
      <div class="col-md-5 col-md-offset-1" id="about-text">
        <h2>Quienes somos</h2>
        <p>Magas del Sur es una empresa formada por un círculo de mujeres 
        alquimistas que se unieron para recrear antiguas recetas mágicas que 
        permiten hacer la vida más sana y vivir en un estado de eterna juventud. 
        Magas del sur trabaja en el Sur del Planeta, desde Argentina para el 
        mundo. Los productos manufacturados por Magas del Sur, están elaborados 
        con aceites esenciales y elementos naturales puros, seleccionados 
        minuciosamente.</p>
      </div>
      <div class="col-md-5" id="about-img">
        <%= image_tag("kit.png", :alt => "magas kit", :width => "500") %>
      </div>
  </div>
</div>

app/views/pages/products.html.erb
<h2>Products Page</h2>